# Generated by Django 4.1.4 on 2023-01-19 06:11

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=80, unique=True, verbose_name='name city')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='advert.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('agreement_price', models.BooleanField()),
                ('phone_number', models.CharField(max_length=12)),
                ('publish', models.BooleanField(default=False, verbose_name=' نمایش آگهی')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('image0', models.ImageField(blank=True, default='defaults/default-thumbnail.jpg', null=True, upload_to='adverts_images/')),
                ('image1', models.ImageField(blank=True, default='defaults/default-thumbnail.jpg', null=True, upload_to='adverts_images/')),
                ('image2', models.ImageField(blank=True, default='defaults/default-thumbnail.jpg', null=True, upload_to='adverts_images/')),
                ('image3', models.ImageField(blank=True, default='defaults/default-thumbnail.jpg', null=True, upload_to='adverts_images/')),
                ('image4', models.ImageField(blank=True, default='defaults/default-thumbnail.jpg', null=True, upload_to='adverts_images/')),
                ('image5', models.ImageField(blank=True, default='defaults/default-thumbnail.jpg', null=True, upload_to='adverts_images/')),
                ('address', models.TextField()),
                ('created_obj', models.DateTimeField(auto_now_add=True)),
                ('status_type', models.CharField(choices=[('نو', 'نو'), ('کارکرده', 'کارکرده')], max_length=30)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advert.brand')),
                ('categorys', mptt.fields.TreeManyToManyField(related_name='adverts', to='advert.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advert.city')),
                ('country_made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advert.country')),
            ],
        ),
    ]
