# Generated by Django 4.1.4 on 2022-12-17 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='country',
            field=models.ForeignKey(blank=True, default='IT', null=True, on_delete=django.db.models.deletion.CASCADE, to='advert.country', to_field='name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
