# Generated by Django 4.1.4 on 2022-12-17 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_alter_advert_country_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='brand',
            field=models.ForeignKey(blank=True, default='نامعلوم', null=True, on_delete=django.db.models.deletion.CASCADE, to='advert.brand', to_field='name'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='country',
            field=models.ForeignKey(blank=True, default='نامعلوم', null=True, on_delete=django.db.models.deletion.CASCADE, to='advert.country', to_field='name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_city',
            field=models.CharField(max_length=80, unique=True, verbose_name='name city'),
        ),
    ]
